[package]
name = "kmeans"
version = "0.1.0"
authors = ["ASNordroid <n3tstrang3r@yandex.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.2"
plotlib = "0.4.0"