[package]
name = "test-sdl2"
version = "0.6.0"
authors = ["ASNordroid <n3tstrang3r@yandex.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.34.2"
rand = "0.7.3"
png = "0.16.7"
rayon = "1.1"
